version: "3.3"
services:
  db:
    image: "postgres:12.8"
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=warehouseuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=logiwise_v1